apiVersion: v1
kind: ConfigMap
metadata:
  name: calculator-api-config
  namespace: calculator
data:
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_URLS: http://0.0.0.0:8080
---
apiVersion: v1
kind: Secret
metadata:
  name: calculator-db-secret
  namespace: calculator
type: Opaque
stringData:
  connection-string: "Host=postgres;Port=5432;Database=calculator;Username=calculator;Password=calculator_pass"
