apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres-pvc.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - calculator-api-config.yaml
  - calculator-api-deployment.yaml
  - calculator-api-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
